package com.loicbaillif.addInst.ess.stand.random;

// Java standard package
import java.util.Random;

// Project packages
import com.loicbaillif.tools.Print;

public class Theory {
    public static void main() {
        Print.title("Theory - Random", '+');

        Print.subtitle("1) Creating pseudorandom generator");
        Random random1 = new Random(); // Seed generated by the system
        Random random2 = new Random(12345); // Uses specified seed

        Print.subtitle("2) Basic Methods");
        System.out.println("***** nextInt():");
        for (int i = 1; i < 6; i++) {
            System.out.printf("***** Run n°%d:%n", i);
            System.out.printf("\trandom.nextInt() with system seed = %s%n",
                    random1.nextInt());
            System.out.printf("\trandom.nextInt() with specified seed = %s%n",
                    random2.nextInt());

        }


        Print.subtitle("End of Theory", '+', (byte) 80);
    }
}
