package com.loicbaillif.addInst.ess.stand.random;

// Java standard package
import java.util.Random;

// Project packages
import com.loicbaillif.tools.Print;

public class Theory {
    public static void main() {
        Print.title("Theory - Random", '+');

        int nbExamples = 2;

        Print.subtitle("1) Creating pseudorandom generator");
        Random random1 = new Random(); // Seed generated by the system
        Random random2 = new Random(100000); // Uses specified seed

        Print.subtitle("2) Basic Methods");
        System.out.println("***** nextInt():");
        for (int i = 1; i <= nbExamples; i++) {
            System.out.printf("***** Run n°%d:%n", i);
            System.out.printf("\trandom.nextInt() with system seed = %s%n",
                    random1.nextInt());
            System.out.printf("\trandom.nextInt() with specified seed = %s%n",
                    random2.nextInt());

        }

        System.out.printf("%n***** nextInt(bound)%n");
        for (int i = 1; i <= nbExamples; i++) {
            System.out.printf("***** Run n°%d:%n", i);
            System.out.printf("\trandom.nextInt(100) with system seed = %s%n",
                    random1.nextInt(100));
            System.out.printf("\trandom.nextInt(100) with specified seed = %s%n",
                    random2.nextInt(100));
        }

        System.out.printf("%n***** nextLong()%n");
        for (int i = 1; i <= nbExamples; i++) {
            System.out.printf("***** Run n°%d:%n", i);
            System.out.printf("\trandom.nextLong() with system seed = %s%n",
                    random1.nextLong());
            System.out.printf("\trandom.nextLong() with specified seed = %s%n",
                    random2.nextLong());
        }

        System.out.printf("%n***** nextDouble()%n");
        for (int i = 1; i <= nbExamples; i++) {
            System.out.printf("***** Run n°%d:%n", i);
            System.out.printf(
                    "\trandom.nextDouble() with system seed = %s%n",
                    random1.nextLong()
            );
            System.out.printf(
                    "\trandom.nextDouble() with specified seed = %s%n",
                    random2.nextLong()
            );
        }

        System.out.printf("%n***** nextBytes()%n");
        byte[] bytes = new byte[10];
        for (int i = 1; i <= nbExamples; i++) {
            System.out.printf("***** Run n°%d:%n", i);
            random1.nextBytes(bytes);
            System.out.printf(
                    "\trandom.nextBytes() with system seed => %n\t\t["
            );
            for (byte aByte : bytes) {
                System.out.printf("%d; ", aByte);
            }
            System.out.printf("]%n");
            random2.nextBytes(bytes);
            System.out.printf(
                    "\trandom.nextBytes() with specified seed => %n\t\t["
            );
            for (byte bByte : bytes) {
                System.out.printf("%d; ", bByte);
            }
            System.out.printf("]%n");
        }


        Print.subtitle("3) Example: printing pseudorandom numbers");
        // Print a random int between lowLimit and highLimit (both included)
        int lowLimit = 33;
        int highLimit = 42;
        int range = highLimit - lowLimit + 1;
        for (int i = 1; i < 10; i++) {
            System.out.println(random1.nextInt(range) + lowLimit);
        }

        Print.subtitle("End of Theory", '+', (byte) 80);
    }
}
