package com.loicbaillif.addInst.ess.stand.random;

// Java standard package
import java.util.Random;

// Project packages
import com.loicbaillif.tools.Print;

public class Theory {
    public static void main() {
        Print.title("Theory - Random", '+');

        Print.subtitle("1) Creating pseudorandom generator");
        Random random1 = new Random(); // Seed generated by the system
        Random random2 = new Random(123456789); // Uses specified seed


        Print.subtitle("End of Theory", '+', (byte) 80);
    }
}
